version: "3.7"

services:
  app:
    depends_on: 
    - mysql
    # image: node:12-alpine
    # command: sh -c "yarn install && yarn run dev"
    # ports:
    #   - 7001:7001
    # working_dir: /app
    # volumes:
    #   - ./:/app
    image: tommyzf/backpzhuweb
    build: .
    ports:
      - "7001:7001"
    volumes: 
      - pzhuweb-back-data:/app
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_DB: pzhuweb2

  mysql:
    image: mysql:5.7
    container_name: pzhuwebmysql
    volumes:
      - pzhuweb-mysql-data:/var/lib/mysql
      - ./mysql:/docker-entrypoint-initdb.d/
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: pzhuweb2

volumes:
  pzhuweb-mysql-data:
  pzhuweb-back-data: