FROM node:14
LABEL author="caihaifei@enjoytoday.cn"

WORKDIR /app
COPY package.json /app/package.json
RUN npm config set registry https://registry.npm.taobao.org
RUN  npm i 
COPY . /app

EXPOSE 7001

CMD  npm run dev